-- glfw | GLFW 3.x
-- auto-generated api from ffi headers
local api=
  {
  ["GLFW_VERSION_MAJOR"] = { type ="value", },
  ["GLFW_VERSION_MINOR"] = { type ="value", },
  ["GLFW_VERSION_REVISION"] = { type ="value", },
  ["GLFW_RELEASE"] = { type ="value", },
  ["GLFW_PRESS"] = { type ="value", },
  ["GLFW_KEY_SPACE"] = { type ="value", },
  ["GLFW_KEY_APOSTROPHE"] = { type ="value", },
  ["GLFW_KEY_COMMA"] = { type ="value", },
  ["GLFW_KEY_MINUS"] = { type ="value", },
  ["GLFW_KEY_PERIOD"] = { type ="value", },
  ["GLFW_KEY_SLASH"] = { type ="value", },
  ["GLFW_KEY_0"] = { type ="value", },
  ["GLFW_KEY_1"] = { type ="value", },
  ["GLFW_KEY_2"] = { type ="value", },
  ["GLFW_KEY_3"] = { type ="value", },
  ["GLFW_KEY_4"] = { type ="value", },
  ["GLFW_KEY_5"] = { type ="value", },
  ["GLFW_KEY_6"] = { type ="value", },
  ["GLFW_KEY_7"] = { type ="value", },
  ["GLFW_KEY_8"] = { type ="value", },
  ["GLFW_KEY_9"] = { type ="value", },
  ["GLFW_KEY_SEMICOLON"] = { type ="value", },
  ["GLFW_KEY_EQUAL"] = { type ="value", },
  ["GLFW_KEY_A"] = { type ="value", },
  ["GLFW_KEY_B"] = { type ="value", },
  ["GLFW_KEY_C"] = { type ="value", },
  ["GLFW_KEY_D"] = { type ="value", },
  ["GLFW_KEY_E"] = { type ="value", },
  ["GLFW_KEY_F"] = { type ="value", },
  ["GLFW_KEY_G"] = { type ="value", },
  ["GLFW_KEY_H"] = { type ="value", },
  ["GLFW_KEY_I"] = { type ="value", },
  ["GLFW_KEY_J"] = { type ="value", },
  ["GLFW_KEY_K"] = { type ="value", },
  ["GLFW_KEY_L"] = { type ="value", },
  ["GLFW_KEY_M"] = { type ="value", },
  ["GLFW_KEY_N"] = { type ="value", },
  ["GLFW_KEY_O"] = { type ="value", },
  ["GLFW_KEY_P"] = { type ="value", },
  ["GLFW_KEY_Q"] = { type ="value", },
  ["GLFW_KEY_R"] = { type ="value", },
  ["GLFW_KEY_S"] = { type ="value", },
  ["GLFW_KEY_T"] = { type ="value", },
  ["GLFW_KEY_U"] = { type ="value", },
  ["GLFW_KEY_V"] = { type ="value", },
  ["GLFW_KEY_W"] = { type ="value", },
  ["GLFW_KEY_X"] = { type ="value", },
  ["GLFW_KEY_Y"] = { type ="value", },
  ["GLFW_KEY_Z"] = { type ="value", },
  ["GLFW_KEY_LEFT_BRACKET"] = { type ="value", },
  ["GLFW_KEY_BACKSLASH"] = { type ="value", },
  ["GLFW_KEY_RIGHT_BRACKET"] = { type ="value", },
  ["GLFW_KEY_GRAVE_ACCENT"] = { type ="value", },
  ["GLFW_KEY_WORLD_1"] = { type ="value", },
  ["GLFW_KEY_WORLD_2"] = { type ="value", },
  ["GLFW_KEY_ESCAPE"] = { type ="value", },
  ["GLFW_KEY_ENTER"] = { type ="value", },
  ["GLFW_KEY_TAB"] = { type ="value", },
  ["GLFW_KEY_BACKSPACE"] = { type ="value", },
  ["GLFW_KEY_INSERT"] = { type ="value", },
  ["GLFW_KEY_DELETE"] = { type ="value", },
  ["GLFW_KEY_RIGHT"] = { type ="value", },
  ["GLFW_KEY_LEFT"] = { type ="value", },
  ["GLFW_KEY_DOWN"] = { type ="value", },
  ["GLFW_KEY_UP"] = { type ="value", },
  ["GLFW_KEY_PAGE_UP"] = { type ="value", },
  ["GLFW_KEY_PAGE_DOWN"] = { type ="value", },
  ["GLFW_KEY_HOME"] = { type ="value", },
  ["GLFW_KEY_END"] = { type ="value", },
  ["GLFW_KEY_CAPS_LOCK"] = { type ="value", },
  ["GLFW_KEY_SCROLL_LOCK"] = { type ="value", },
  ["GLFW_KEY_NUM_LOCK"] = { type ="value", },
  ["GLFW_KEY_PRINT_SCREEN"] = { type ="value", },
  ["GLFW_KEY_PAUSE"] = { type ="value", },
  ["GLFW_KEY_F1"] = { type ="value", },
  ["GLFW_KEY_F2"] = { type ="value", },
  ["GLFW_KEY_F3"] = { type ="value", },
  ["GLFW_KEY_F4"] = { type ="value", },
  ["GLFW_KEY_F5"] = { type ="value", },
  ["GLFW_KEY_F6"] = { type ="value", },
  ["GLFW_KEY_F7"] = { type ="value", },
  ["GLFW_KEY_F8"] = { type ="value", },
  ["GLFW_KEY_F9"] = { type ="value", },
  ["GLFW_KEY_F10"] = { type ="value", },
  ["GLFW_KEY_F11"] = { type ="value", },
  ["GLFW_KEY_F12"] = { type ="value", },
  ["GLFW_KEY_F13"] = { type ="value", },
  ["GLFW_KEY_F14"] = { type ="value", },
  ["GLFW_KEY_F15"] = { type ="value", },
  ["GLFW_KEY_F16"] = { type ="value", },
  ["GLFW_KEY_F17"] = { type ="value", },
  ["GLFW_KEY_F18"] = { type ="value", },
  ["GLFW_KEY_F19"] = { type ="value", },
  ["GLFW_KEY_F20"] = { type ="value", },
  ["GLFW_KEY_F21"] = { type ="value", },
  ["GLFW_KEY_F22"] = { type ="value", },
  ["GLFW_KEY_F23"] = { type ="value", },
  ["GLFW_KEY_F24"] = { type ="value", },
  ["GLFW_KEY_F25"] = { type ="value", },
  ["GLFW_KEY_KP_0"] = { type ="value", },
  ["GLFW_KEY_KP_1"] = { type ="value", },
  ["GLFW_KEY_KP_2"] = { type ="value", },
  ["GLFW_KEY_KP_3"] = { type ="value", },
  ["GLFW_KEY_KP_4"] = { type ="value", },
  ["GLFW_KEY_KP_5"] = { type ="value", },
  ["GLFW_KEY_KP_6"] = { type ="value", },
  ["GLFW_KEY_KP_7"] = { type ="value", },
  ["GLFW_KEY_KP_8"] = { type ="value", },
  ["GLFW_KEY_KP_9"] = { type ="value", },
  ["GLFW_KEY_KP_DECIMAL"] = { type ="value", },
  ["GLFW_KEY_KP_DIVIDE"] = { type ="value", },
  ["GLFW_KEY_KP_MULTIPLY"] = { type ="value", },
  ["GLFW_KEY_KP_SUBTRACT"] = { type ="value", },
  ["GLFW_KEY_KP_ADD"] = { type ="value", },
  ["GLFW_KEY_KP_ENTER"] = { type ="value", },
  ["GLFW_KEY_KP_EQUAL"] = { type ="value", },
  ["GLFW_KEY_LEFT_SHIFT"] = { type ="value", },
  ["GLFW_KEY_LEFT_CONTROL"] = { type ="value", },
  ["GLFW_KEY_LEFT_ALT"] = { type ="value", },
  ["GLFW_KEY_LEFT_SUPER"] = { type ="value", },
  ["GLFW_KEY_RIGHT_SHIFT"] = { type ="value", },
  ["GLFW_KEY_RIGHT_CONTROL"] = { type ="value", },
  ["GLFW_KEY_RIGHT_ALT"] = { type ="value", },
  ["GLFW_KEY_RIGHT_SUPER"] = { type ="value", },
  ["GLFW_KEY_MENU"] = { type ="value", },
  ["GLFW_KEY_LAST"] = { type ="value", },
  ["GLFW_MOUSE_BUTTON_1"] = { type ="value", },
  ["GLFW_MOUSE_BUTTON_2"] = { type ="value", },
  ["GLFW_MOUSE_BUTTON_3"] = { type ="value", },
  ["GLFW_MOUSE_BUTTON_4"] = { type ="value", },
  ["GLFW_MOUSE_BUTTON_5"] = { type ="value", },
  ["GLFW_MOUSE_BUTTON_6"] = { type ="value", },
  ["GLFW_MOUSE_BUTTON_7"] = { type ="value", },
  ["GLFW_MOUSE_BUTTON_8"] = { type ="value", },
  ["GLFW_MOUSE_BUTTON_LAST"] = { type ="value", },
  ["GLFW_MOUSE_BUTTON_LEFT"] = { type ="value", },
  ["GLFW_MOUSE_BUTTON_RIGHT"] = { type ="value", },
  ["GLFW_MOUSE_BUTTON_MIDDLE"] = { type ="value", },
  ["GLFW_JOYSTICK_1"] = { type ="value", },
  ["GLFW_JOYSTICK_2"] = { type ="value", },
  ["GLFW_JOYSTICK_3"] = { type ="value", },
  ["GLFW_JOYSTICK_4"] = { type ="value", },
  ["GLFW_JOYSTICK_5"] = { type ="value", },
  ["GLFW_JOYSTICK_6"] = { type ="value", },
  ["GLFW_JOYSTICK_7"] = { type ="value", },
  ["GLFW_JOYSTICK_8"] = { type ="value", },
  ["GLFW_JOYSTICK_9"] = { type ="value", },
  ["GLFW_JOYSTICK_10"] = { type ="value", },
  ["GLFW_JOYSTICK_11"] = { type ="value", },
  ["GLFW_JOYSTICK_12"] = { type ="value", },
  ["GLFW_JOYSTICK_13"] = { type ="value", },
  ["GLFW_JOYSTICK_14"] = { type ="value", },
  ["GLFW_JOYSTICK_15"] = { type ="value", },
  ["GLFW_JOYSTICK_16"] = { type ="value", },
  ["GLFW_JOYSTICK_LAST"] = { type ="value", },
  ["GLFW_WINDOWED"] = { type ="value", },
  ["GLFW_FULLSCREEN"] = { type ="value", },
  ["GLFW_ACTIVE"] = { type ="value", },
  ["GLFW_ICONIFIED"] = { type ="value", },
  ["GLFW_ACCELERATED"] = { type ="value", },
  ["GLFW_RED_BITS"] = { type ="value", },
  ["GLFW_GREEN_BITS"] = { type ="value", },
  ["GLFW_BLUE_BITS"] = { type ="value", },
  ["GLFW_ALPHA_BITS"] = { type ="value", },
  ["GLFW_DEPTH_BITS"] = { type ="value", },
  ["GLFW_STENCIL_BITS"] = { type ="value", },
  ["GLFW_REFRESH_RATE"] = { type ="value", },
  ["GLFW_ACCUM_RED_BITS"] = { type ="value", },
  ["GLFW_ACCUM_GREEN_BITS"] = { type ="value", },
  ["GLFW_ACCUM_BLUE_BITS"] = { type ="value", },
  ["GLFW_ACCUM_ALPHA_BITS"] = { type ="value", },
  ["GLFW_AUX_BUFFERS"] = { type ="value", },
  ["GLFW_STEREO"] = { type ="value", },
  ["GLFW_WINDOW_NO_RESIZE"] = { type ="value", },
  ["GLFW_FSAA_SAMPLES"] = { type ="value", },
  ["GLFW_OPENGL_VERSION_MAJOR"] = { type ="value", },
  ["GLFW_OPENGL_VERSION_MINOR"] = { type ="value", },
  ["GLFW_OPENGL_FORWARD_COMPAT"] = { type ="value", },
  ["GLFW_OPENGL_DEBUG_CONTEXT"] = { type ="value", },
  ["GLFW_OPENGL_PROFILE"] = { type ="value", },
  ["GLFW_OPENGL_CORE_PROFILE"] = { type ="value", },
  ["GLFW_OPENGL_COMPAT_PROFILE"] = { type ="value", },
  ["GLFW_OPENGL_ES2_PROFILE"] = { type ="value", },
  ["GLFW_MOUSE_CURSOR"] = { type ="value", },
  ["GLFW_STICKY_KEYS"] = { type ="value", },
  ["GLFW_STICKY_MOUSE_BUTTONS"] = { type ="value", },
  ["GLFW_SYSTEM_KEYS"] = { type ="value", },
  ["GLFW_KEY_REPEAT"] = { type ="value", },
  ["GLFW_PRESENT"] = { type ="value", },
  ["GLFW_AXES"] = { type ="value", },
  ["GLFW_BUTTONS"] = { type ="value", },
  ["GLFW_NO_ERROR"] = { type ="value", },
  ["GLFW_NOT_INITIALIZED"] = { type ="value", },
  ["GLFW_NO_CURRENT_WINDOW"] = { type ="value", },
  ["GLFW_INVALID_ENUM"] = { type ="value", },
  ["GLFW_INVALID_VALUE"] = { type ="value", },
  ["GLFW_OUT_OF_MEMORY"] = { type ="value", },
  ["GLFW_OPENGL_UNAVAILABLE"] = { type ="value", },
  ["GLFW_VERSION_UNAVAILABLE"] = { type ="value", },
  ["GLFW_PLATFORM_ERROR"] = { type ="value", },
  ["GLFW_GAMMA_RAMP_SIZE"] = { type ="value", },
  ["glfwInit"] = { type ="function",
    description = "",
    returns = "(int)",
    args = "(void)", },
  ["glfwTerminate"] = { type ="function",
    description = "",
    returns = "()",
    args = "(void)", },
  ["glfwGetVersion"] = { type ="function",
    description = "",
    returns = "()",
    args = "(int* major, int* minor, int* rev)", },
  ["glfwGetVersionString"] = { type ="function",
    description = "",
    returns = "(const char*)",
    valuetype = "string",
    args = "(void)", },
  ["glfwGetError"] = { type ="function",
    description = "",
    returns = "(int)",
    args = "(void)", },
  ["glfwErrorString"] = { type ="function",
    description = "",
    returns = "(const char*)",
    valuetype = "string",
    args = "(int error)", },
  ["glfwGetVideoModes"] = { type ="function",
    description = "",
    returns = "(int)",
    args = "(GLFWvidmode* list, int maxcount)", },
  ["glfwGetDesktopMode"] = { type ="function",
    description = "",
    returns = "()",
    args = "(GLFWvidmode* mode)", },
  ["glfwSetGammaFormula"] = { type ="function",
    description = "",
    returns = "()",
    args = "(float gamma, float blacklevel, float gain)", },
  ["glfwGetGammaRamp"] = { type ="function",
    description = "",
    returns = "()",
    args = "(GLFWgammaramp* ramp)", },
  ["glfwSetGammaRamp"] = { type ="function",
    description = "",
    returns = "()",
    args = "(const GLFWgammaramp* ramp)", },
  ["glfwOpenWindow"] = { type ="function",
    description = "",
    returns = "(GLFWwindow)",
    args = "(int width, int height, int mode, const char* title, GLFWwindow share)", },
  ["glfwOpenWindowHint"] = { type ="function",
    description = "",
    returns = "()",
    args = "(int target, int hint)", },
  ["glfwMakeWindowCurrent"] = { type ="function",
    description = "",
    returns = "()",
    args = "(GLFWwindow window)", },
  ["glfwIsWindow"] = { type ="function",
    description = "",
    returns = "(int)",
    args = "(GLFWwindow window)", },
  ["glfwGetCurrentWindow"] = { type ="function",
    description = "",
    returns = "(GLFWwindow)",
    args = "(void)", },
  ["glfwCloseWindow"] = { type ="function",
    description = "",
    returns = "()",
    args = "(GLFWwindow window)", },
  ["glfwSetWindowTitle"] = { type ="function",
    description = "",
    returns = "()",
    args = "(GLFWwindow, const char* title)", },
  ["glfwGetWindowSize"] = { type ="function",
    description = "",
    returns = "()",
    args = "(GLFWwindow, int* width, int* height)", },
  ["glfwSetWindowSize"] = { type ="function",
    description = "",
    returns = "()",
    args = "(GLFWwindow, int width, int height)", },
  ["glfwGetWindowPos"] = { type ="function",
    description = "",
    returns = "()",
    args = "(GLFWwindow, int* x, int* y)", },
  ["glfwSetWindowPos"] = { type ="function",
    description = "",
    returns = "()",
    args = "(GLFWwindow, int x, int y)", },
  ["glfwIconifyWindow"] = { type ="function",
    description = "",
    returns = "()",
    args = "(GLFWwindow window)", },
  ["glfwRestoreWindow"] = { type ="function",
    description = "",
    returns = "()",
    args = "(GLFWwindow window)", },
  ["glfwGetWindowParam"] = { type ="function",
    description = "",
    returns = "(int)",
    args = "(GLFWwindow window, int param)", },
  ["glfwSetWindowUserPointer"] = { type ="function",
    description = "",
    returns = "()",
    args = "(GLFWwindow window, void* pointer)", },
  ["glfwGetWindowUserPointer"] = { type ="function",
    description = "",
    returns = "(void*)",
    args = "(GLFWwindow window)", },
  ["glfwPollEvents"] = { type ="function",
    description = "",
    returns = "()",
    args = "(void)", },
  ["glfwWaitEvents"] = { type ="function",
    description = "",
    returns = "()",
    args = "(void)", },
  ["glfwGetKey"] = { type ="function",
    description = "",
    returns = "(int)",
    args = "(GLFWwindow window, int key)", },
  ["glfwGetMouseButton"] = { type ="function",
    description = "",
    returns = "(int)",
    args = "(GLFWwindow window, int button)", },
  ["glfwGetMousePos"] = { type ="function",
    description = "",
    returns = "()",
    args = "(GLFWwindow window, int* xpos, int* ypos)", },
  ["glfwSetMousePos"] = { type ="function",
    description = "",
    returns = "()",
    args = "(GLFWwindow window, int xpos, int ypos)", },
  ["glfwGetScrollOffset"] = { type ="function",
    description = "",
    returns = "()",
    args = "(GLFWwindow window, int* x, int* y)", },
  ["glfwGetJoystickParam"] = { type ="function",
    description = "",
    returns = "(int)",
    args = "(int joy, int param)", },
  ["glfwGetJoystickPos"] = { type ="function",
    description = "",
    returns = "(int)",
    args = "(int joy, float* pos, int numaxes)", },
  ["glfwGetJoystickButtons"] = { type ="function",
    description = "",
    returns = "(int)",
    args = "(int joy, unsigned char* buttons, int numbuttons)", },
  ["glfwGetTime"] = { type ="function",
    description = "",
    returns = "(double)",
    args = "(void)", },
  ["glfwSetTime"] = { type ="function",
    description = "",
    returns = "()",
    args = "(double time)", },
  ["glfwSwapBuffers"] = { type ="function",
    description = "",
    returns = "()",
    args = "(void)", },
  ["glfwSwapInterval"] = { type ="function",
    description = "",
    returns = "()",
    args = "(int interval)", },
  ["glfwExtensionSupported"] = { type ="function",
    description = "",
    returns = "(int)",
    args = "(const char* extension)", },
  ["glfwGetProcAddress"] = { type ="function",
    description = "",
    returns = "(void*)",
    args = "(const char* procname)", },
  ["glfwGetGLVersion"] = { type ="function",
    description = "",
    returns = "()",
    args = "(int* major, int* minor, int* rev)", },
  ["glfwEnable"] = { type ="function",
    description = "",
    returns = "()",
    args = "(GLFWwindow window, int token)", },
  ["glfwDisable"] = { type ="function",
    description = "",
    returns = "()",
    args = "(GLFWwindow window, int token)", },
  ["GLFWvidmode"] = { type ="class",
    description = "",
    childs =
    {
    ["width"] = { type ="value", description = "int", },
    ["height"] = { type ="value", description = "int", },
    ["redBits"] = { type ="value", description = "int", },
    ["blueBits"] = { type ="value", description = "int", },
    ["greenBits"] = { type ="value", description = "int", },
    } },
  ["GLFWgammaramp"] = { type ="class",
    description = "",
    childs =
    {
    ["red"] = { type ="value", description = "unsigned short[GLFW_GAMMA_RAMP_SIZE]", },
    ["green"] = { type ="value", description = "unsigned short[GLFW_GAMMA_RAMP_SIZE]", },
    ["blue"] = { type ="value", description = "unsigned short[GLFW_GAMMA_RAMP_SIZE]", },
    } },
  }

return {
  glfw = {
    type = "lib",
    description = "GLFW window manager",
    childs = api,
  },
}
